prefix:
  "gdrive/MyDrive/Raman_machine_learning/models/v0.4.6/10.finetune_yolo_nonobj_0.2_L2_1e-0/"
trainer: "fit"
optimizer:
        lr: 5e-4
        type: "AdamW"
        weight_decay: 1e-0
# checkpoint: "gdrive/MyDrive/Raman_machine_learning/models/v0.4.3/19.finetune_lr_te-4/default/version_0/checkpoints/epoch=1909-step=217739.ckpt"
