prefix:
  "/home/jlx/v0.4.1/4.self_attention_in_nodes_heads_3/"
model:
  num_of_megnetblock : 10
trainer: "fit"
optimizer:
        lr: 1e-3
        type: "AdamW"
        weight_decay: 1e-2
#checkpoint: "/home/jlx/v0.4.1/3.self_attention_in_nodes/default/version_0/checkpoints/epoch=941-step=106445.ckpt"
