prefix:
  "gdrive/MyDrive/Raman_machine_learning/models/v0.4.3/4.pretrain_fmten_head_8/"
trainer: "fit"
optimizer:
        lr: 1e-3
        type: "Adam"
#checkpoint: "gdrive/MyDrive/Raman_machine_learning/models/v0.4.3/3.pretrain_fmt_en_embedded/default/version_0/checkpoints/epoch=65-step=99989.ckpt"
