prefix:
  "/home/jlx/v0.4.4/15.finetune_loss_weight_4_sign/"
trainer: "fit"
optimizer:
        lr: 5e-4
        type: "Adam"
# checkpoint: "gdrive/MyDrive/Raman_machine_learning/models/v0.4.3/19.finetune_lr_te-4/default/version_0/checkpoints/epoch=1909-step=217739.ckpt"
