prefix:
  "/home/jlx/v0.4.2/10.fintune_keep_before_block_4/"
model:
  num_of_megnetblock : 10
trainer: "fit"
optimizer:
        lr: 1e-3
        type: "AdamW"
        weight_decay: 1e-2
#checkpoint: "/home/jlx/v0.3.10/5.10_layer_original_megnet/default/version_0/checkpoints/epoch=977-step=110513.ckpt"
