prefix:
  "gdrive/MyDrive/Raman_machine_learning/models/v0.4.5/25.finetune_outdim_uneq_25_weight_3_lr_5e-4_weight_decay_1e-2/"
trainer: "fit"
optimizer:
        lr: 5e-4
        type: "AdamW"
        weight_decay: 1e-2
# checkpoint: "gdrive/MyDrive/Raman_machine_learning/models/v0.4.3/19.finetune_lr_te-4/default/version_0/checkpoints/epoch=1909-step=217739.ckpt"
