prefix:
  "gdrive/MyDrive/Raman_machine_learning/models/v0.4.5/20.finetune_outdim_uneq_50_weight_6/"
trainer: "fit"
optimizer:
        lr: 5e-4
        type: "Adam"
# checkpoint: "gdrive/MyDrive/Raman_machine_learning/models/v0.4.3/19.finetune_lr_te-4/default/version_0/checkpoints/epoch=1909-step=217739.ckpt"
