prefix:
  "/home/jlx/v0.4.6/1.pretrain_fmten_layers_8/"
trainer: "fit"
optimizer:
        lr: 5e-4
        type: "AdamW"
# checkpoint: "gdrive/MyDrive/Raman_machine_learning/models/v0.4.3/19.finetune_lr_te-4/default/version_0/checkpoints/epoch=1909-step=217739.ckpt"
