prefix:
  "/home/jlx/v0.4.4/6.Train_atomic_weight/"
trainer: "fit"
optimizer:
        lr: 4e-3
        type: "Adam"
# checkpoint: "gdrive/MyDrive/Raman_machine_learning/models/v0.4.3/19.finetune_lr_te-4/default/version_0/checkpoints/epoch=1909-step=217739.ckpt"
