prefix:
  "/home/jlx/v0.4.1/3.TransformerConv_atom_layer_norm/"
model:
  num_of_megnetblock : 10
trainer: "fit"
optimizer:
        lr: 1e-3
        type: "AdamW"
        weight_decay: 1e-2
#checkpoint: "/home/jlx/v0.4.0/5.7_atom_fea/default/version_0/checkpoints/epoch=974-step=110174.ckpt"
