prefix:
  "gdrive/MyDrive/Raman_machine_learning/models/v0.4.3/18.finetune_hamming/"
trainer: "fit"
optimizer:
        lr: 1e-3
        type: "Adam"
checkpoint: "gdrive/MyDrive/Raman_machine_learning/models/v0.4.3/15.finetune_for_pretrain_14/default/version_1/checkpoints/epoch=2908-step=331625.ckpt"
