prefix:
  "/home/jlx/v0.4.1/4.num_20/"
model:
  num_of_megnetblock : 20
trainer: "fit"
optimizer:
        lr: 1e-3
        type: "AdamW"
        weight_decay: 1e-2
checkpoint: "/home/jlx/v0.4.1/4.num_20/default/version_0/checkpoints/epoch=926-step=104750.ckpt"
