prefix:
  "gdrive/MyDrive/Raman_machine_learning/models/v0.4.3/9.pretrain_fmten_embedding_128/"
trainer: "fit"
optimizer:
        lr: 1e-3
        type: "Adam"
checkpoint: "gdrive/MyDrive/Raman_machine_learning/models/v0.4.3/9.pretrain_fmten_embedding_128/default/version_0/checkpoints/epoch=101-step=154529.ckpt"
